package com.github.diogogdias.bisfinder;

import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

/**
 * Every item name the ported calculator special-cases.
 *
 * <p>The optimizer prunes a slot's items by comparing their accuracy and strength bonuses, which is
 * sound only for items whose entire contribution is those two numbers. An item on this list has an
 * effect the calculator applies by name — a set bonus, a target-specific multiplier, a bolt proc — so
 * pruning it on raw bonuses would throw away a setup that actually wins. Membership here only stops an
 * item being pruned, so a name that is not really an item is harmless.
 *
 * <p>Generated from the string literals in BaseCalc, PlayerVsNpcCalc and Equipment. Regenerate it if
 * the port is updated from upstream.
 */
final class EffectItems
{
	private static final Set<String> NAMES = Collections.unmodifiableSet(new HashSet<>(Arrays.asList(
		"Abyssal bludgeon",
		"Abyssal dagger",
		"Abyssal tentacle",
		"Abyssal whip",
		"Accursed sceptre",
		"Accursed sceptre (a)",
		"Adamant pickaxe",
		"Ahrim's hood",
		"Ahrim's robeskirt",
		"Ahrim's robetop",
		"Ahrim's staff",
		"Amethyst broad bolts",
		"Amulet of avarice",
		"Amulet of the damned",
		"Ancient godsword",
		"Arclight",
		"Armadyl godsword",
		"Bandos godsword",
		"Barronite mace",
		"Berserker necklace",
		"Berserker necklace (or)",
		"Black mask",
		"Black mask (i)",
		"Black pickaxe",
		"Black salamander",
		"Blast",
		"Blazing blowpipe",
		"Blessed axe",
		"Blessed dizana's quiver",
		"Blisterwood flail",
		"Blisterwood sickle",
		"Blisterwood stake",
		"Blood moon chestplate",
		"Blood moon helm",
		"Blood moon tassets",
		"Blue moon chestplate",
		"Blue moon helm",
		"Blue moon spear",
		"Blue moon tassets",
		"Bolt",
		"Bone claws",
		"Bone mace",
		"Bone shortbow",
		"Bone staff",
		"Bow of faerdhinen",
		"Brimstone ring",
		"Broad arrows",
		"Broad bolts",
		"Bronze pickaxe",
		"Burning claws",
		"Burst of Strength",
		"Cave kraken",
		"Chaos gauntlets",
		"Charged",
		"Claws of Guthix",
		"Clone",
		"Colossal blade",
		"Comp ogre bow",
		"Confliction gauntlets",
		"Corporeal Beast",
		"Corrupted staff (attuned)",
		"Corrupted staff (basic)",
		"Corrupted staff (perfected)",
		"Craw's bow",
		"Crumble Undead",
		"Crystal blessing",
		"Crystal body",
		"Crystal bow",
		"Crystal helm",
		"Crystal legs",
		"Crystal staff (attuned)",
		"Crystal staff (basic)",
		"Crystal staff (perfected)",
		"Dark bow",
		"Darklight",
		"Dawnbringer",
		"Demonbane",
		"Dharok's greataxe",
		"Dharok's helm",
		"Dharok's platebody",
		"Dharok's platelegs",
		"Diamond bolts (e)",
		"Diamond dragon bolts (e)",
		"Dinh's blazing bulwark",
		"Dinh's bulwark",
		"Dizana's max cape",
		"Dizana's quiver",
		"Dragon hunter crossbow",
		"Dragon hunter lance",
		"Dragon hunter wand",
		"Dragonstone bolts (e)",
		"Dragonstone dragon bolts (e)",
		"Dual macuahuitl",
		"Duke Sucellus",
		"Earthbound tecpatl",
		"Echo boots",
		"Eclipse atlatl",
		"Eclipse moon chestplate",
		"Eclipse moon helm",
		"Eclipse moon tassets",
		"Efaritay's aid",
		"Elite void robe",
		"Elite void robe (or)",
		"Elite void top",
		"Elite void top (or)",
		"Emberlight",
		"Emerald sickle",
		"Emerald sickle (b)",
		"Enchanted emerald sickle (b)",
		"Enchanted ruby sickle (b)",
		"Eye of ayak",
		"Fareed",
		"Fire Warrior of Lesarkus",
		"Flames of Zamarok",
		"Flames of Zamorak",
		"Fragment of Seren",
		"Gadderhammer",
		"Gilded pickaxe",
		"Glacial temotli",
		"Granite hammer",
		"Guthix cape",
		"Guthix max cape",
		"Guthix staff",
		"Hallowed flail",
		"Harmonised nightmare staff",
		"Holy sanguinesti staff",
		"Holy water",
		"Hunter's spear",
		"Iban Blast",
		"Iban's staff",
		"Iban's staff (u)",
		"Ice arrows",
		"Imbued guthix cape",
		"Imbued guthix max cape",
		"Imbued saradomin cape",
		"Imbued saradomin max cape",
		"Imbued zamorak cape",
		"Imbued zamorak max cape",
		"Inquisitor's great helm",
		"Inquisitor's hauberk",
		"Inquisitor's mace",
		"Inquisitor's plateskirt",
		"Iron pickaxe",
		"Ivandis flail",
		"Justiciar chestguard",
		"Justiciar faceguard",
		"Justiciar legguards",
		"Karil's coif",
		"Karil's crossbow",
		"Karil's leatherskirt",
		"Karil's leathertop",
		"Keris",
		"Keris partisan of amascut",
		"Keris partisan of breaching",
		"Keris partisan of the sun",
		"Kraken",
		"Leaf-bladed battleaxe",
		"Leaf-bladed spear",
		"Leaf-bladed sword",
		"Magic Dart",
		"Magic comp bow",
		"Magic longbow",
		"Magic shortbow",
		"Magic shortbow (i)",
		"Melee Punish",
		"Mithril pickaxe",
		"Mystic smoke staff",
		"Nezikchened",
		"Normal",
		"Obsidian helmet",
		"Obsidian platebody",
		"Obsidian platelegs",
		"Ogre bow",
		"Onyx bolts (e)",
		"Onyx dragon bolts (e)",
		"Opal bolts (e)",
		"Opal dragon bolts (e)",
		"Orange salamander",
		"Osmumten's fang",
		"Osmumten's fang (or)",
		"Out of Melee Range",
		"Pearl bolts (e)",
		"Pearl dragon bolts (e)",
		"Phase 1",
		"Purging staff",
		"Red salamander",
		"Respiratory system",
		"Revenant",
		"Ring of recoil",
		"Ring of suffering",
		"Ring of suffering (i)",
		"Rod of ivandis",
		"Ruby bolts (e)",
		"Ruby dragon bolts (e)",
		"Ruby sickle (b)",
		"Rune pickaxe",
		"Salve amulet",
		"Salve amulet (e)",
		"Salve amulet(ei)",
		"Salve amulet(i)",
		"Sanguinesti staff",
		"Saradomin Strike",
		"Saradomin cape",
		"Saradomin godsword",
		"Saradomin max cape",
		"Saradomin staff",
		"Scorching bow",
		"Scythe of vitur",
		"Seeking",
		"Sharp Eye",
		"Shielded",
		"Silver bolts#Poison",
		"Silver bolts#Poison+",
		"Silver bolts#Poison++",
		"Silver bolts#Unpoisoned",
		"Silver sickle",
		"Silver sickle (b)",
		"Silverlight",
		"Silverlight (dyed)",
		"Skogre",
		"Slagilith",
		"Slash Bash",
		"Slayer helmet",
		"Slayer helmet (i)",
		"Slayer's staff",
		"Slayer's staff (e)",
		"Smoke battlestaff",
		"Soulreaper axe",
		"Staff of balance",
		"Staff of light",
		"Staff of the dead",
		"Starter staff",
		"Steel pickaxe",
		"Sulphur blades",
		"Sunspear",
		"Swamp lizard",
		"Tecu salamander",
		"Thammaron's sceptre",
		"Thammaron's sceptre (a)",
		"Toktz-mej-tal",
		"Toktz-xil-ak",
		"Toktz-xil-ek",
		"Tome of earth",
		"Tome of fire",
		"Tome of water",
		"Tonalztics of ralos",
		"Torag's hammers",
		"Torag's helm",
		"Torag's platebody",
		"Torag's platelegs",
		"Tormented Demon",
		"Toxic blowpipe",
		"Toxic staff of the dead",
		"Transition",
		"Trident of the seas",
		"Trident of the seas (e)",
		"Trident of the swamp",
		"Trident of the swamp (e)",
		"Tumeken's shadow",
		"Twinflame staff",
		"Twisted bow",
		"Tzhaar-ket-em",
		"Tzhaar-ket-om",
		"Tzhaar-ket-om (t)",
		"Unshielded",
		"Ursine chainmace",
		"V's helm",
		"Verac's brassard",
		"Verac's flail",
		"Verac's helm",
		"Verac's plateskirt",
		"Verzik Vitur",
		"Viggora's chainmace",
		"Virtus",
		"Void knight gloves",
		"Void knight mace",
		"Void knight robe",
		"Void knight robe (or)",
		"Void knight top",
		"Void knight top (or)",
		"Void mage helm",
		"Void mage helm (or)",
		"Void melee helm",
		"Void melee helm (or)",
		"Void ranger helm",
		"Void ranger helm (or)",
		"Warped sceptre",
		"Wave",
		"Webweaver bow",
		"With Pillar",
		"Wolfbane",
		"Your weapon requires ammo to use.",
		"Zamorak cape",
		"Zamorak godsword",
		"Zamorak max cape",
		"Zamorak staff",
		"Zaryte crossbow",
		"Zogre",
		"Zulrah"
	)));

	private EffectItems()
	{
	}

	static boolean matters(String itemName)
	{
		return NAMES.contains(itemName);
	}
}
